// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOgFW0up-wul3gDq5OUZxQVPE-SbqDVwY',
    appId: '1:1090161770992:web:f26d8fffea903eb7309d35',
    messagingSenderId: '1090161770992',
    projectId: 'hackaton-b9205',
    authDomain: 'hackaton-b9205.firebaseapp.com',
    storageBucket: 'hackaton-b9205.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqymNbyv2c19wcDX5wXrf9R5GFF-LJrvY',
    appId: '1:1090161770992:android:3b8884167021162d309d35',
    messagingSenderId: '1090161770992',
    projectId: 'hackaton-b9205',
    storageBucket: 'hackaton-b9205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm_IvhqsEi3b8PJwbLZ-RyrDtj92zzh4E',
    appId: '1:1090161770992:ios:5af014aaa8ffc820309d35',
    messagingSenderId: '1090161770992',
    projectId: 'hackaton-b9205',
    storageBucket: 'hackaton-b9205.appspot.com',
    iosBundleId: 'com.example.topicosProy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm_IvhqsEi3b8PJwbLZ-RyrDtj92zzh4E',
    appId: '1:1090161770992:ios:5af014aaa8ffc820309d35',
    messagingSenderId: '1090161770992',
    projectId: 'hackaton-b9205',
    storageBucket: 'hackaton-b9205.appspot.com',
    iosBundleId: 'com.example.topicosProy',
  );
}
